/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Checkbox: typeof import('primevue/checkbox')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    LabelledCheckbox: typeof import('./src/components/LabelledCheckbox.vue')['default']
    NumberInputGroup: typeof import('./src/components/NumberInputGroup.vue')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
  }
}
